name: NASA Project CI
on:
    push:
        branches: [ master ]
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v3
            - name: Use Node.js Version 20
              uses: action/setup-node@v3
              with:
                node-verions: '20'
            - run: npm install
            - run: npm run build --prefix client